"use client";

import { useState, useEffect, useRef } from "react";
import { TabId } from "../AppShell";
import { getDailyBriefing, saveDailyBriefing } from "@/lib/storage";
import { getTodayString } from "@/lib/utils";
import { DailyBriefing, CaptureAnalysis } from "@/lib/types";
import {
  formatDate,
  formatTime,
  getJudgmentStyle,
  getCountryFlag,
  getStockTypeStyle,
} from "@/lib/utils";
import {
  Camera,
  RefreshCw,
  ChevronRight,
  AlertCircle,
  Zap,
  Loader2,
  CheckCircle2,
  X,
  Plus,
} from "lucide-react";

interface BriefingTabProps {
  onNavigate: (tab: TabId, options?: { stockId?: string; query?: string }) => void;
}

interface CaptureItem {
  id: string;
  imageData: string;
  analyzing: boolean;
  analysis: CaptureAnalysis | null;
  error: boolean;
}

// Canvas로 이미지 압축
async function compressImage(file: File): Promise<string> {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const img = new window.Image();
      img.onload = () => {
        const MAX = 900;
        let { width, height } = img;
        if (width > MAX || height > MAX) {
          if (width > height) { height = Math.round((height * MAX) / width); width = MAX; }
          else { width = Math.round((width * MAX) / height); height = MAX; }
        }
        const canvas = document.createElement("canvas");
        canvas.width = width; canvas.height = height;
        canvas.getContext("2d")!.drawImage(img, 0, 0, width, height);
        resolve(canvas.toDataURL("image/jpeg", 0.82));
      };
      img.src = e.target?.result as string;
    };
    reader.readAsDataURL(file);
  });
}

export default function BriefingTab({ onNavigate }: BriefingTabProps) {
  const [briefing, setBriefing] = useState<DailyBriefing | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [captures, setCaptures] = useState<CaptureItem[]>([]);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const today = new Date();

  useEffect(() => {
    // 로컬 브리핑 먼저 표시
    const local = getDailyBriefing();
    if (local) setBriefing(local);

    // KV에서 최신 브리핑 조회
    const todayStr = getTodayString();
    fetch("/api/briefing/latest")
      .then((r) => r.json())
      .then(({ briefing: kv }) => {
        if (!kv || kv.date !== todayStr) return;
        const localTime = local ? new Date(local.generatedAt).getTime() : 0;
        if (new Date(kv.generatedAt).getTime() > localTime) {
          saveDailyBriefing(kv);
          setBriefing(kv);
          setIsAutoGenerated(true);
        }
      })
      .catch(() => {});
  }, []);

  // 파일 선택 → 압축 → Vision 분석 → 자동 브리핑
  async function handleFiles(files: FileList) {
    const newItems: CaptureItem[] = [];

    for (const file of Array.from(files)) {
      const id = Math.random().toString(36).slice(2, 8);
      const imageData = await compressImage(file);
      newItems.push({ id, imageData, analyzing: true, analysis: null, error: false });
    }

    setCaptures((prev) => [...prev, ...newItems]);
    setError(null);

    // 각 캡처 분석
    const analyzed = await Promise.all(
      newItems.map(async (item) => {
        try {
          const res = await fetch("/api/analyze-capture", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ stockId: item.id, slot: "morning", imageData: item.imageData }),
          });
          if (!res.ok) throw new Error();
          const data = await res.json();
          return { ...item, analyzing: false, analysis: data.analysis as CaptureAnalysis };
        } catch {
          return { ...item, analyzing: false, error: true };
        }
      })
    );

    setCaptures((prev) => {
      const map = Object.fromEntries(analyzed.map((a) => [a.id, a]));
      return prev.map((c) => map[c.id] ?? c);
    });

    // 분석 완료된 캡처가 있으면 자동 브리핑 시작
    const valid = analyzed.filter((a) => a.analysis?.stockName || a.analysis?.currentPrice);
    if (valid.length > 0) {
      const allAnalyses = [...captures.filter(c => c.analysis), ...valid]
        .map(c => c.analysis)
        .filter(Boolean) as CaptureAnalysis[];
      await runBriefing(allAnalyses);
    }
  }

  async function runBriefing(capturedStocks?: CaptureAnalysis[]) {
    setLoading(true);
    setError(null);
    try {
      const stocks = capturedStocks ?? captures.map(c => c.analysis).filter(Boolean) as CaptureAnalysis[];
      const res = await fetch("/api/generate-briefing", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ stocks: [], capturedStocks: stocks, useWebSearch: true }),
      });
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error || "브리핑 생성 실패");
      }
      const data: DailyBriefing = await res.json();
      saveDailyBriefing(data);
      setBriefing(data);
      setIsAutoGenerated(false);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "오류가 발생했습니다");
    } finally {
      setLoading(false);
    }
  }

  function removeCapture(id: string) {
    setCaptures((prev) => prev.filter((c) => c.id !== id));
  }

  const hasAnalyzedCaptures = captures.some(c => c.analysis);
  const allDoneAnalyzing = captures.length > 0 && captures.every(c => !c.analyzing);

  return (
    <div className="tab-content">
      {/* 헤더 */}
      <div className="sticky top-0 bg-white border-b border-gray-100 px-4 py-3 z-10">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-xs text-gray-400">{formatDate(today)}</p>
            {briefing && (
              <div className="flex items-center gap-2 mt-0.5">
                <p className="text-xs text-gray-400">생성: {formatTime(briefing.generatedAt)}</p>
                {isAutoGenerated && (
                  <span className="flex items-center gap-0.5 text-[10px] font-semibold text-emerald-600 bg-emerald-50 px-1.5 py-0.5 rounded-full border border-emerald-200">
                    <Zap size={9} /> 자동생성
                  </span>
                )}
              </div>
            )}
          </div>
          {/* 캡처 없이 수동으로 브리핑 재생성 */}
          {briefing && (
            <button
              onClick={() => runBriefing()}
              disabled={loading}
              className="flex items-center gap-1.5 text-xs text-gray-400 active:text-gray-600"
            >
              <RefreshCw size={13} className={loading ? "animate-spin" : ""} />
              새로고침
            </button>
          )}
        </div>
      </div>

      <div className="px-4 py-4 space-y-4">
        {/* ── 오늘 캡처 올리기 (메인 CTA) ── */}
        <input
          ref={fileRef}
          type="file"
          accept="image/*"
          multiple
          className="hidden"
          onChange={(e) => { if (e.target.files?.length) handleFiles(e.target.files); e.target.value = ""; }}
        />

        <button
          onClick={() => fileRef.current?.click()}
          disabled={loading}
          className="w-full bg-violet-600 active:bg-violet-700 disabled:opacity-50 rounded-2xl p-5 flex flex-col items-center gap-2 transition-all shadow-md shadow-violet-200"
        >
          <div className="w-14 h-14 bg-white/20 rounded-full flex items-center justify-center">
            {loading ? (
              <Loader2 size={28} className="text-white animate-spin" />
            ) : (
              <Camera size={28} className="text-white" />
            )}
          </div>
          <div className="text-center">
            <p className="text-white font-bold text-base">
              {loading ? "AI 분석 중..." : "오늘 캡처 올리기"}
            </p>
            <p className="text-violet-200 text-xs mt-0.5">
              {loading
                ? "잠깐만요, 브리핑을 만들고 있어요"
                : "MTS 화면을 올리면 AI가 바로 분석해요"}
            </p>
          </div>
        </button>

        {/* ── 업로드된 캡처 목록 ── */}
        {captures.length > 0 && (
          <div>
            <div className="flex items-center justify-between mb-2">
              <p className="text-xs font-semibold text-gray-500">
                업로드된 캡처 {captures.length}장
              </p>
              {allDoneAnalyzing && hasAnalyzedCaptures && !loading && (
                <button
                  onClick={() => runBriefing()}
                  className="text-xs text-violet-600 font-medium flex items-center gap-0.5"
                >
                  <RefreshCw size={11} /> 다시 분석
                </button>
              )}
            </div>
            <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-hide">
              {captures.map((cap) => (
                <CaptureCard
                  key={cap.id}
                  item={cap}
                  onRemove={() => removeCapture(cap.id)}
                />
              ))}
              {/* 추가 업로드 버튼 */}
              <button
                onClick={() => fileRef.current?.click()}
                className="shrink-0 w-20 h-28 rounded-xl border-2 border-dashed border-gray-200 flex flex-col items-center justify-center gap-1"
              >
                <Plus size={18} className="text-gray-300" />
                <span className="text-[10px] text-gray-300">추가</span>
              </button>
            </div>
          </div>
        )}

        {/* 오류 */}
        {error && (
          <div className="flex items-start gap-2 bg-red-50 border border-red-200 rounded-xl p-3">
            <AlertCircle size={15} className="text-red-500 mt-0.5 shrink-0" />
            <p className="text-sm text-red-700">{error}</p>
          </div>
        )}

        {/* 브리핑 없고 캡처도 없는 초기 상태 */}
        {!briefing && !loading && captures.length === 0 && (
          <div className="text-center py-8">
            <p className="text-gray-300 text-sm">위 버튼을 눌러 MTS 화면을 올려보세요</p>
            <p className="text-gray-300 text-xs mt-1">종목 등록 없이 바로 분석됩니다</p>
          </div>
        )}

        {/* 로딩 스켈레톤 */}
        {loading && !briefing && <LoadingSkeleton />}

        {/* ── 브리핑 결과 ── */}
        {briefing && !loading && (
          <>
            <Section title="오늘 시장 요약">
              <div className="bg-gray-50 rounded-xl p-4">
                <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-line">
                  {briefing.marketSummary}
                </p>
              </div>
            </Section>

            {briefing.stockBriefings.length > 0 && (
              <Section title="내 종목 오늘 결정">
                <div className="space-y-3">
                  {briefing.stockBriefings.map((sb) => {
                    const style = getJudgmentStyle(sb.judgment);
                    return (
                      <button
                        key={sb.stockId}
                        onClick={() => onNavigate("news", { stockId: sb.stockId })}
                        className="w-full text-left bg-white border border-gray-100 rounded-xl p-4 shadow-sm active:bg-gray-50"
                      >
                        <div className="flex items-start justify-between gap-2">
                          <div className="flex items-center gap-2">
                            <span>{getCountryFlag(sb.country)}</span>
                            <span className="font-semibold text-sm text-gray-900">{sb.stockName}</span>
                            {sb.currentPrice && (
                              <span className="text-xs text-gray-400">{sb.currentPrice}</span>
                            )}
                          </div>
                          <div className="flex items-center gap-1 shrink-0">
                            <span className={`text-xs font-medium px-2 py-0.5 rounded-full border ${style.bg} ${style.text} ${style.border}`}>
                              {style.label}
                            </span>
                            {sb.returnRate && (
                              <span className={`text-xs font-bold ${sb.returnRate.startsWith("+") ? "text-red-500" : "text-blue-500"}`}>
                                {sb.returnRate}
                              </span>
                            )}
                          </div>
                        </div>
                        <p className="mt-2 text-xs text-gray-500 leading-relaxed line-clamp-2">{sb.summary}</p>
                        {sb.newsPreview.length > 0 && (
                          <div className="mt-2 space-y-0.5">
                            {sb.newsPreview.slice(0, 2).map((n, i) => (
                              <p key={i} className="text-xs text-gray-400 truncate">· {n}</p>
                            ))}
                          </div>
                        )}
                      </button>
                    );
                  })}
                </div>
              </Section>
            )}

            {briefing.recommendedStocks.length > 0 && (
              <Section title="오늘의 추천종목">
                <div className="space-y-3">
                  {briefing.recommendedStocks.map((rec, i) => {
                    const typeStyle = getStockTypeStyle(rec.type);
                    return (
                      <div key={i} className="bg-white border border-gray-100 rounded-xl p-4 shadow-sm">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <span>{getCountryFlag(rec.country)}</span>
                            <span className="font-semibold text-sm text-gray-900">{rec.name}</span>
                            <span className="text-xs text-gray-400">{rec.code}</span>
                          </div>
                          <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${typeStyle.bg} ${typeStyle.text}`}>
                            {typeStyle.label}
                          </span>
                        </div>
                        <p className="mt-2 text-xs text-gray-600 leading-relaxed">{rec.reason}</p>
                        <ul className="mt-2 space-y-1">
                          {rec.bullets.map((b, j) => (
                            <li key={j} className="text-xs text-gray-500 flex gap-1.5">
                              <span className="text-violet-400 shrink-0">•</span>{b}
                            </li>
                          ))}
                        </ul>
                        <div className="mt-3 flex items-center justify-between">
                          <span className="text-xs text-gray-400">
                            목표가 <span className="font-semibold text-gray-700">{rec.targetPrice}</span>
                          </span>
                          <button
                            onClick={() => onNavigate("ai", { query: `${rec.name}(${rec.code}) 지금 매수 시점이 적절한지 분석해줘.` })}
                            className="text-xs text-violet-600 font-medium flex items-center gap-0.5"
                          >
                            AI 상담 <ChevronRight size={12} />
                          </button>
                        </div>
                      </div>
                    );
                  })}
                </div>
                <p className="text-xs text-gray-400 text-center mt-3 px-2">
                  투자 판단의 참고 자료이며, 실제 매매는 본인 책임 하에 결정하세요.
                </p>
              </Section>
            )}
          </>
        )}
      </div>
    </div>
  );
}

// ── 캡처 카드 ──
function CaptureCard({ item, onRemove }: { item: CaptureItem; onRemove: () => void }) {
  return (
    <div className="shrink-0 w-20 rounded-xl overflow-hidden border border-gray-100 relative" style={{ height: "7rem" }}>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={item.imageData} alt="캡처" className="w-full h-full object-cover" />

      {/* 분석 중 오버레이 */}
      {item.analyzing && (
        <div className="absolute inset-0 bg-black/50 flex flex-col items-center justify-center gap-1">
          <Loader2 size={16} className="text-white animate-spin" />
          <span className="text-white text-[9px]">분석 중</span>
        </div>
      )}

      {/* 완료 오버레이 */}
      {!item.analyzing && !item.error && item.analysis && (
        <div className="absolute bottom-0 left-0 right-0 bg-black/60 px-1.5 py-1">
          <p className="text-white text-[9px] font-semibold truncate">
            {item.analysis.stockName ?? "인식됨"}
          </p>
          {item.analysis.returnRate && (
            <p className={`text-[9px] font-bold ${item.analysis.returnRate.startsWith("+") ? "text-red-400" : "text-blue-300"}`}>
              {item.analysis.returnRate}
            </p>
          )}
        </div>
      )}

      {/* 에러 */}
      {item.error && (
        <div className="absolute inset-0 bg-red-500/60 flex items-center justify-center">
          <span className="text-white text-[9px]">인식 실패</span>
        </div>
      )}

      {/* 완료 뱃지 */}
      {!item.analyzing && !item.error && (
        <div className="absolute top-1 right-1">
          <CheckCircle2 size={13} className="text-emerald-400" />
        </div>
      )}

      {/* 삭제 버튼 */}
      <button
        onClick={onRemove}
        className="absolute top-1 left-1 w-4 h-4 bg-black/50 rounded-full flex items-center justify-center"
      >
        <X size={9} className="text-white" />
      </button>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-sm font-bold text-gray-800 mb-3 flex items-center gap-2">
        <span className="w-1 h-4 bg-violet-500 rounded-full inline-block" />
        {title}
      </h2>
      {children}
    </div>
  );
}

function LoadingSkeleton() {
  return (
    <div className="space-y-5 animate-pulse">
      {[1, 2, 3].map((i) => (
        <div key={i} className="space-y-2">
          <div className="h-4 bg-gray-200 rounded w-1/3" />
          <div className="h-24 bg-gray-100 rounded-xl" />
        </div>
      ))}
    </div>
  );
}
